version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5672:5672"
      - "15672:15672"
  pingservice:
    image: ping-service
    build:
      context: .
      dockerfile: PingService/Dockerfile
    ports:
      - "9090:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
  pongservice:
    image: pong-service
    build:
      context: .
      dockerfile: PongService/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      rabbitmq:
        condition: service_healthy