version: "3"
services:
  logging-sidecar:
    container_name: fluentd_logger
    build:
      context: .
      dockerfile: fluentd/Dockerfile
    volumes:
      - ./fluentd/conf:/fluentd/etc
    environment:
      FLUENTD_CONF: "fluent.conf"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    expose:
      - "9200"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./config.hcl:/vault/config/config.hcl:ro
      - ./vault_data:/vault/data
    cap_add:
        - IPC_LOCK
    command: server
    restart: always
  rabbitmq:
    user: "999"
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5672:5672"
      - "15672:15672"
  apigateway:
    image: api-gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
  authservice:
    image: auth-service
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
  pingservice:
    image: ping-service
    links:
      - logging-sidecar
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "docker.pingservice"
    build:
      context: .
      dockerfile: PingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq:
        condition: service_healthy
  pongservice:
    image: pong-service
    links:
      - logging-sidecar
    logging:
      driver: "fluentd"
      options:
          fluentd-address: localhost:24224
          tag: "docker.pongservice"
    build:
      context: .
      dockerfile: PongService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq:
        condition: service_healthy