version: "3"
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./config.hcl:/vault/config/config.hcl:ro
      - ./vault_data:/vault/data
    cap_add:
        - IPC_LOCK
    command: server
    restart: always
    networks:
      - microservices
      - default
  rabbitmq:
    user: "999"
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    networks:
      - microservices
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5672:5672"
      - "15672:15672"
  apigateway:
    image: api-gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8081:80"
    networks:
      - microservices
      - default
    depends_on:
      rabbitmq:
        condition: service_healthy
  authservice:
    image: auth-service
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    networks:
      - microservices
    depends_on:
      rabbitmq:
        condition: service_healthy
  pingservice:
    image: ping-service
    build:
      context: .
      dockerfile: PingService/Dockerfile
    networks:
      - microservices
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq:
        condition: service_healthy
  pongservice:
    image: pong-service
    build:
      context: .
      dockerfile: PongService/Dockerfile
    networks:
      - microservices
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  microservices:
    internal: true