version: "3"
services:
  rabbitmq:
    user: "999"
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5672:5672"
      - "15672:15672"
  apigateway:
    image: api-gateway
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8081:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
  authservice:
    image: auth-service
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    ports:
      - "9191:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
  pingservice:
    image: ping-service
    build:
      context: .
      dockerfile: PingService/Dockerfile
    ports:
      - "9090:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      rabbitmq:
        condition: service_healthy
  pongservice:
    image: pong-service
    build:
      context: .
      dockerfile: PongService/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      rabbitmq:
        condition: service_healthy