apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  rabbitmq:
    additionalConfig: |
      default_user = guest
      default_pass = guest
      loopback_users = none