apiVersion: v1
kind: Service
metadata:
  name: pingservice
  namespace: default
spec:
  type: NodePort
  selector:
    app: pingservice
  ports:
    - port: 80
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingservice
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pingservice
  template:
    metadata:
      labels:
        app: pingservice
    spec:
      containers:
        - name: pingservice
          image: pingpongexample/pingservice
          imagePullPolicy: Never
          env:
            - name: PONG_SERVICE_URL
              value: "http://pongservice"